// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: guild_settings.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearActivePlaylist = `-- name: ClearActivePlaylist :exec
DELETE FROM active_playlists WHERE guild_id = $1
`

func (q *Queries) ClearActivePlaylist(ctx context.Context, guildID string) error {
	_, err := q.db.Exec(ctx, clearActivePlaylist, guildID)
	return err
}

const getActivePlaylist = `-- name: GetActivePlaylist :one
SELECT 
    ap.guild_id,
    ap.playlist_id,
    ap.activated_at,
    ap.activated_by,
    p.name AS playlist_name
FROM active_playlists ap
LEFT JOIN playlists p ON ap.playlist_id = p.id
WHERE ap.guild_id = $1
`

type GetActivePlaylistRow struct {
	GuildID      string      `json:"guild_id"`
	PlaylistID   pgtype.UUID `json:"playlist_id"`
	ActivatedAt  time.Time   `json:"activated_at"`
	ActivatedBy  *string     `json:"activated_by"`
	PlaylistName *string     `json:"playlist_name"`
}

func (q *Queries) GetActivePlaylist(ctx context.Context, guildID string) (*GetActivePlaylistRow, error) {
	row := q.db.QueryRow(ctx, getActivePlaylist, guildID)
	var i GetActivePlaylistRow
	err := row.Scan(
		&i.GuildID,
		&i.PlaylistID,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.PlaylistName,
	)
	return &i, err
}

const getGuildSettings = `-- name: GetGuildSettings :one
SELECT guild_id, default_volume, auto_disconnect_minutes, announce_songs, restrict_to_dj_role, dj_role_id, default_repeat_mode, updated_at FROM guild_settings WHERE guild_id = $1
`

func (q *Queries) GetGuildSettings(ctx context.Context, guildID string) (*GuildSetting, error) {
	row := q.db.QueryRow(ctx, getGuildSettings, guildID)
	var i GuildSetting
	err := row.Scan(
		&i.GuildID,
		&i.DefaultVolume,
		&i.AutoDisconnectMinutes,
		&i.AnnounceSongs,
		&i.RestrictToDjRole,
		&i.DjRoleID,
		&i.DefaultRepeatMode,
		&i.UpdatedAt,
	)
	return &i, err
}

const setActivePlaylist = `-- name: SetActivePlaylist :one
INSERT INTO active_playlists (guild_id, playlist_id, activated_by)
VALUES ($1, $2, $3)
ON CONFLICT (guild_id) DO UPDATE SET 
    playlist_id = EXCLUDED.playlist_id,
    activated_at = NOW(),
    activated_by = EXCLUDED.activated_by
RETURNING guild_id, playlist_id, activated_at, activated_by
`

type SetActivePlaylistParams struct {
	GuildID     string      `json:"guild_id"`
	PlaylistID  pgtype.UUID `json:"playlist_id"`
	ActivatedBy *string     `json:"activated_by"`
}

func (q *Queries) SetActivePlaylist(ctx context.Context, arg SetActivePlaylistParams) (*ActivePlaylist, error) {
	row := q.db.QueryRow(ctx, setActivePlaylist, arg.GuildID, arg.PlaylistID, arg.ActivatedBy)
	var i ActivePlaylist
	err := row.Scan(
		&i.GuildID,
		&i.PlaylistID,
		&i.ActivatedAt,
		&i.ActivatedBy,
	)
	return &i, err
}

const upsertGuildSettings = `-- name: UpsertGuildSettings :one
INSERT INTO guild_settings (
    guild_id, 
    default_volume, 
    auto_disconnect_minutes, 
    announce_songs,
    restrict_to_dj_role,
    dj_role_id,
    default_repeat_mode
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (guild_id) DO UPDATE SET
    default_volume = COALESCE(EXCLUDED.default_volume, guild_settings.default_volume),
    auto_disconnect_minutes = COALESCE(EXCLUDED.auto_disconnect_minutes, guild_settings.auto_disconnect_minutes),
    announce_songs = COALESCE(EXCLUDED.announce_songs, guild_settings.announce_songs),
    restrict_to_dj_role = COALESCE(EXCLUDED.restrict_to_dj_role, guild_settings.restrict_to_dj_role),
    dj_role_id = COALESCE(EXCLUDED.dj_role_id, guild_settings.dj_role_id),
    default_repeat_mode = COALESCE(EXCLUDED.default_repeat_mode, guild_settings.default_repeat_mode),
    updated_at = NOW()
RETURNING guild_id, default_volume, auto_disconnect_minutes, announce_songs, restrict_to_dj_role, dj_role_id, default_repeat_mode, updated_at
`

type UpsertGuildSettingsParams struct {
	GuildID               string  `json:"guild_id"`
	DefaultVolume         *int32  `json:"default_volume"`
	AutoDisconnectMinutes *int32  `json:"auto_disconnect_minutes"`
	AnnounceSongs         *bool   `json:"announce_songs"`
	RestrictToDjRole      *bool   `json:"restrict_to_dj_role"`
	DjRoleID              *string `json:"dj_role_id"`
	DefaultRepeatMode     *string `json:"default_repeat_mode"`
}

func (q *Queries) UpsertGuildSettings(ctx context.Context, arg UpsertGuildSettingsParams) (*GuildSetting, error) {
	row := q.db.QueryRow(ctx, upsertGuildSettings,
		arg.GuildID,
		arg.DefaultVolume,
		arg.AutoDisconnectMinutes,
		arg.AnnounceSongs,
		arg.RestrictToDjRole,
		arg.DjRoleID,
		arg.DefaultRepeatMode,
	)
	var i GuildSetting
	err := row.Scan(
		&i.GuildID,
		&i.DefaultVolume,
		&i.AutoDisconnectMinutes,
		&i.AnnounceSongs,
		&i.RestrictToDjRole,
		&i.DjRoleID,
		&i.DefaultRepeatMode,
		&i.UpdatedAt,
	)
	return &i, err
}
