// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: guilds.sql

package database

import (
	"context"
)

const deleteGuild = `-- name: DeleteGuild :exec
DELETE FROM guilds WHERE id = $1
`

func (q *Queries) DeleteGuild(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGuild, id)
	return err
}

const getGuild = `-- name: GetGuild :one
SELECT id, name, joined_at, settings FROM guilds WHERE id = $1
`

func (q *Queries) GetGuild(ctx context.Context, id string) (*Guild, error) {
	row := q.db.QueryRow(ctx, getGuild, id)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.JoinedAt,
		&i.Settings,
	)
	return &i, err
}

const listGuilds = `-- name: ListGuilds :many
SELECT id, name, joined_at, settings FROM guilds ORDER BY joined_at DESC
`

func (q *Queries) ListGuilds(ctx context.Context) ([]*Guild, error) {
	rows, err := q.db.Query(ctx, listGuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Guild{}
	for rows.Next() {
		var i Guild
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.JoinedAt,
			&i.Settings,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGuild = `-- name: UpsertGuild :one
INSERT INTO guilds (id, name, joined_at)
VALUES ($1, $2, NOW())
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, joined_at, settings
`

type UpsertGuildParams struct {
	ID   string  `json:"id"`
	Name *string `json:"name"`
}

func (q *Queries) UpsertGuild(ctx context.Context, arg UpsertGuildParams) (*Guild, error) {
	row := q.db.QueryRow(ctx, upsertGuild, arg.ID, arg.Name)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.JoinedAt,
		&i.Settings,
	)
	return &i, err
}
