// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivePlaylist struct {
	GuildID     string      `json:"guild_id"`
	PlaylistID  pgtype.UUID `json:"playlist_id"`
	ActivatedAt time.Time   `json:"activated_at"`
	ActivatedBy *string     `json:"activated_by"`
}

type Guild struct {
	ID       string    `json:"id"`
	Name     *string   `json:"name"`
	JoinedAt time.Time `json:"joined_at"`
	Settings []byte    `json:"settings"`
}

type GuildSetting struct {
	GuildID               string    `json:"guild_id"`
	DefaultVolume         *int32    `json:"default_volume"`
	AutoDisconnectMinutes *int32    `json:"auto_disconnect_minutes"`
	AnnounceSongs         *bool     `json:"announce_songs"`
	RestrictToDjRole      *bool     `json:"restrict_to_dj_role"`
	DjRoleID              *string   `json:"dj_role_id"`
	DefaultRepeatMode     *string   `json:"default_repeat_mode"`
	UpdatedAt             time.Time `json:"updated_at"`
}

type PlayHistory struct {
	ID              uuid.UUID `json:"id"`
	GuildID         *string   `json:"guild_id"`
	OriginalInput   string    `json:"original_input"`
	SourceType      string    `json:"source_type"`
	Title           *string   `json:"title"`
	PlayedBy        *string   `json:"played_by"`
	PlayedAt        time.Time `json:"played_at"`
	DurationSeconds *int32    `json:"duration_seconds"`
	Completed       *bool     `json:"completed"`
}

type Playlist struct {
	ID          uuid.UUID `json:"id"`
	GuildID     *string   `json:"guild_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsPublic    *bool     `json:"is_public"`
	CreatedBy   *string   `json:"created_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type PlaylistEntry struct {
	ID              uuid.UUID `json:"id"`
	PlaylistID      uuid.UUID `json:"playlist_id"`
	OriginalInput   string    `json:"original_input"`
	SourceType      string    `json:"source_type"`
	Title           *string   `json:"title"`
	DurationSeconds *int32    `json:"duration_seconds"`
	ThumbnailUrl    *string   `json:"thumbnail_url"`
	Position        int32     `json:"position"`
	AddedBy         *string   `json:"added_by"`
	AddedAt         time.Time `json:"added_at"`
}

type UserFavorite struct {
	ID            uuid.UUID `json:"id"`
	UserID        string    `json:"user_id"`
	OriginalInput string    `json:"original_input"`
	SourceType    string    `json:"source_type"`
	Title         *string   `json:"title"`
	AddedAt       time.Time `json:"added_at"`
}
