// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: playlists.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (guild_id, name, description, is_public, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, guild_id, name, description, is_public, created_by, created_at, updated_at
`

type CreatePlaylistParams struct {
	GuildID     *string `json:"guild_id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsPublic    *bool   `json:"is_public"`
	CreatedBy   *string `json:"created_by"`
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (*Playlist, error) {
	row := q.db.QueryRow(ctx, createPlaylist,
		arg.GuildID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
		arg.CreatedBy,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists WHERE id = $1
`

func (q *Queries) DeletePlaylist(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlaylist, id)
	return err
}

const deletePlaylistByName = `-- name: DeletePlaylistByName :exec
DELETE FROM playlists 
WHERE name = $1 AND (guild_id = $2 OR guild_id IS NULL)
`

type DeletePlaylistByNameParams struct {
	Name    string  `json:"name"`
	GuildID *string `json:"guild_id"`
}

func (q *Queries) DeletePlaylistByName(ctx context.Context, arg DeletePlaylistByNameParams) error {
	_, err := q.db.Exec(ctx, deletePlaylistByName, arg.Name, arg.GuildID)
	return err
}

const getPlaylistByID = `-- name: GetPlaylistByID :one
SELECT id, guild_id, name, description, is_public, created_by, created_at, updated_at FROM playlists WHERE id = $1
`

func (q *Queries) GetPlaylistByID(ctx context.Context, id uuid.UUID) (*Playlist, error) {
	row := q.db.QueryRow(ctx, getPlaylistByID, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPlaylistByName = `-- name: GetPlaylistByName :one
SELECT id, guild_id, name, description, is_public, created_by, created_at, updated_at FROM playlists 
WHERE name = $1 AND (guild_id = $2 OR guild_id IS NULL)
LIMIT 1
`

type GetPlaylistByNameParams struct {
	Name    string  `json:"name"`
	GuildID *string `json:"guild_id"`
}

func (q *Queries) GetPlaylistByName(ctx context.Context, arg GetPlaylistByNameParams) (*Playlist, error) {
	row := q.db.QueryRow(ctx, getPlaylistByName, arg.Name, arg.GuildID)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPlaylistByNameAndGuild = `-- name: GetPlaylistByNameAndGuild :one
SELECT id, guild_id, name, description, is_public, created_by, created_at, updated_at FROM playlists 
WHERE name = $1 AND (guild_id = $2 OR guild_id IS NULL)
ORDER BY guild_id NULLS LAST
LIMIT 1
`

type GetPlaylistByNameAndGuildParams struct {
	Name    string  `json:"name"`
	GuildID *string `json:"guild_id"`
}

func (q *Queries) GetPlaylistByNameAndGuild(ctx context.Context, arg GetPlaylistByNameAndGuildParams) (*Playlist, error) {
	row := q.db.QueryRow(ctx, getPlaylistByNameAndGuild, arg.Name, arg.GuildID)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listPlaylists = `-- name: ListPlaylists :many
SELECT 
    p.id,
    p.guild_id,
    p.name,
    p.description,
    p.is_public,
    p.created_by,
    p.created_at,
    p.updated_at,
    COUNT(pe.id)::int AS entry_count
FROM playlists p
LEFT JOIN playlist_entries pe ON p.id = pe.playlist_id
WHERE p.guild_id = $1 OR $1 IS NULL
GROUP BY p.id
ORDER BY p.name
`

type ListPlaylistsRow struct {
	ID          uuid.UUID `json:"id"`
	GuildID     *string   `json:"guild_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsPublic    *bool     `json:"is_public"`
	CreatedBy   *string   `json:"created_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	EntryCount  int32     `json:"entry_count"`
}

// List all playlists, optionally filtered by guild
func (q *Queries) ListPlaylists(ctx context.Context, guildID *string) ([]*ListPlaylistsRow, error) {
	rows, err := q.db.Query(ctx, listPlaylists, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListPlaylistsRow{}
	for rows.Next() {
		var i ListPlaylistsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByGuild = `-- name: ListPlaylistsByGuild :many
SELECT 
    p.id,
    p.guild_id,
    p.name,
    p.description,
    p.is_public,
    p.created_by,
    p.created_at,
    p.updated_at,
    COUNT(pe.id)::int AS entry_count
FROM playlists p
LEFT JOIN playlist_entries pe ON p.id = pe.playlist_id
WHERE p.guild_id = $1 OR p.guild_id IS NULL
GROUP BY p.id
ORDER BY p.name
`

type ListPlaylistsByGuildRow struct {
	ID          uuid.UUID `json:"id"`
	GuildID     *string   `json:"guild_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsPublic    *bool     `json:"is_public"`
	CreatedBy   *string   `json:"created_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	EntryCount  int32     `json:"entry_count"`
}

func (q *Queries) ListPlaylistsByGuild(ctx context.Context, guildID *string) ([]*ListPlaylistsByGuildRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistsByGuild, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListPlaylistsByGuildRow{}
	for rows.Next() {
		var i ListPlaylistsByGuildRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playlistExists = `-- name: PlaylistExists :one
SELECT EXISTS(
    SELECT 1 FROM playlists 
    WHERE name = $1 AND (guild_id = $2 OR guild_id IS NULL)
)
`

type PlaylistExistsParams struct {
	Name    string  `json:"name"`
	GuildID *string `json:"guild_id"`
}

func (q *Queries) PlaylistExists(ctx context.Context, arg PlaylistExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, playlistExists, arg.Name, arg.GuildID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePlaylist = `-- name: UpdatePlaylist :one
UPDATE playlists
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    is_public = COALESCE($4, is_public)
WHERE id = $1
RETURNING id, guild_id, name, description, is_public, created_by, created_at, updated_at
`

type UpdatePlaylistParams struct {
	ID          uuid.UUID `json:"id"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
	IsPublic    *bool     `json:"is_public"`
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (*Playlist, error) {
	row := q.db.QueryRow(ctx, updatePlaylist,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updatePlaylistName = `-- name: UpdatePlaylistName :exec
UPDATE playlists
SET name = $2, updated_at = NOW()
WHERE id = $1
`

type UpdatePlaylistNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdatePlaylistName(ctx context.Context, arg UpdatePlaylistNameParams) error {
	_, err := q.db.Exec(ctx, updatePlaylistName, arg.ID, arg.Name)
	return err
}
