// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddPlaylistEntry(ctx context.Context, arg AddPlaylistEntryParams) (*PlaylistEntry, error)
	AddToPlayHistory(ctx context.Context, arg AddToPlayHistoryParams) (*PlayHistory, error)
	AddUserFavorite(ctx context.Context, arg AddUserFavoriteParams) (*UserFavorite, error)
	ClearActivePlaylist(ctx context.Context, guildID string) error
	ClearPlayHistory(ctx context.Context, guildID *string) error
	CountPlaylistEntries(ctx context.Context, playlistID uuid.UUID) (int32, error)
	CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (*Playlist, error)
	DeleteGuild(ctx context.Context, id string) error
	DeletePlaylist(ctx context.Context, id uuid.UUID) error
	DeletePlaylistByName(ctx context.Context, arg DeletePlaylistByNameParams) error
	DeletePlaylistEntriesByPlaylistID(ctx context.Context, playlistID uuid.UUID) error
	DeletePlaylistEntry(ctx context.Context, id uuid.UUID) error
	DeletePlaylistEntryByInput(ctx context.Context, arg DeletePlaylistEntryByInputParams) error
	EntryExistsInPlaylist(ctx context.Context, arg EntryExistsInPlaylistParams) (bool, error)
	GetActivePlaylist(ctx context.Context, guildID string) (*GetActivePlaylistRow, error)
	GetGuild(ctx context.Context, id string) (*Guild, error)
	GetGuildSettings(ctx context.Context, guildID string) (*GuildSetting, error)
	GetMostPlayedSongs(ctx context.Context, arg GetMostPlayedSongsParams) ([]*GetMostPlayedSongsRow, error)
	GetPlaylistByID(ctx context.Context, id uuid.UUID) (*Playlist, error)
	GetPlaylistByName(ctx context.Context, arg GetPlaylistByNameParams) (*Playlist, error)
	GetPlaylistByNameAndGuild(ctx context.Context, arg GetPlaylistByNameAndGuildParams) (*Playlist, error)
	GetPlaylistEntry(ctx context.Context, id uuid.UUID) (*PlaylistEntry, error)
	GetPlaylistEntryByInput(ctx context.Context, arg GetPlaylistEntryByInputParams) (*PlaylistEntry, error)
	GetPlaylistWithEntries(ctx context.Context, arg GetPlaylistWithEntriesParams) ([]*GetPlaylistWithEntriesRow, error)
	GetRecentPlayHistory(ctx context.Context, arg GetRecentPlayHistoryParams) ([]*PlayHistory, error)
	GetUserFavorites(ctx context.Context, userID string) ([]*UserFavorite, error)
	IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error)
	ListGuilds(ctx context.Context) ([]*Guild, error)
	ListPlaylistEntries(ctx context.Context, playlistID uuid.UUID) ([]*PlaylistEntry, error)
	// List all playlists, optionally filtered by guild
	ListPlaylists(ctx context.Context, guildID *string) ([]*ListPlaylistsRow, error)
	ListPlaylistsByGuild(ctx context.Context, guildID *string) ([]*ListPlaylistsByGuildRow, error)
	MarkPlayCompleted(ctx context.Context, id uuid.UUID) error
	PlaylistExists(ctx context.Context, arg PlaylistExistsParams) (bool, error)
	RemoveUserFavorite(ctx context.Context, arg RemoveUserFavoriteParams) error
	ReorderPlaylistEntry(ctx context.Context, arg ReorderPlaylistEntryParams) error
	SetActivePlaylist(ctx context.Context, arg SetActivePlaylistParams) (*ActivePlaylist, error)
	UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (*Playlist, error)
	UpdatePlaylistEntry(ctx context.Context, arg UpdatePlaylistEntryParams) (*PlaylistEntry, error)
	UpdatePlaylistName(ctx context.Context, arg UpdatePlaylistNameParams) error
	UpsertGuild(ctx context.Context, arg UpsertGuildParams) (*Guild, error)
	UpsertGuildSettings(ctx context.Context, arg UpsertGuildSettingsParams) (*GuildSetting, error)
}

var _ Querier = (*Queries)(nil)
