services:
  postgres:
    image: postgres:16-alpine
    container_name: music-bot-db
    hostname: postgres
    restart: unless-stopped
    
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-music_bot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-music_bot_db_pass}
      POSTGRES_DB: ${POSTGRES_DB:-music_bot}
      TZ: Asia/Ho_Chi_Minh
    
    ports:
      - "5432:5432"
    
    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-music_bot} -d ${POSTGRES_DB:-music_bot}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M

networks:
  default:
    name: music-bot-network
    external: true

volumes:
  db_data:
