services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-music-bot
    
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    restart: unless-stopped
    
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - LOG_LEVEL=info
    
    volumes:
      - ./playlist:/app/playlist:rw
      - ./logs:/app/logs:rw
    
    healthcheck:
      test: ["CMD", "pgrep", "music-bot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"